# Generated by Django 4.2.4 on 2023-12-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('recipe', models.CharField(max_length=5000)),
                ('genre', models.CharField(choices=[('lc', 'Local'), ('ip', 'Importé')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Desert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('recipe', models.CharField(max_length=5000)),
                ('sold', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('bl', 'Blé'), ('ma', 'Maïs'), ('ar', 'Arachides')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('recipe', models.CharField(max_length=5000)),
                ('sold', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('su', 'Sucrée'), ('fe', 'Fermentée'), ('al', 'Alcoolisée')], max_length=5)),
            ],
        ),
    ]
